#!/bin/sh
alias py3="python3 -m ptpython"
alias py2="python2 -m ptpython"
alias grin="grep -rin"
alias duh="du -hd1"
alias lash="ls -alh"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias shrug='echo "¯\_(ツ)_/¯"'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
