[tool_alias]
bat = "aqua:sharkdp/bat"
ripgrep = "aqua:BurntSushi/ripgrep"
jq = "aqua:jqlang/jq"
fd = "aqua:sharkdp/fd"
asciinema = "aqua:asciinema/asciinema"

[tools]
bat = "latest"
fzf = "latest"
ripgrep = "latest"
jq = "latest"
fd = "latest"
asciinema = "latest"
