# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
# Use custom format
format = """
$username$hostname:$directory\
$git_branch\
$line_break\
$character\
"""

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
style = "yellow"

[hostname]
ssh_only = false
format = "[@$hostname](bold green)"
disabled = false

[git_branch]
style = "white"
format = "\\([$branch(:$remote_branch)]($style)\\)"
truncation_length = 12
truncation_symbol = "..."
ignore_branches = []
